### ISSUE TITLE
Need to update documentation or rename branch

### ISSUE THREAD

**Issue by yieldhog** [bendikwa/esphome-igrill#18]
Documentation has:
```
external_components:
  - source: github://bendikwa/esphome-igrill@v1.2
```

The branch has an extra '.' ie github://bendikwa/esphome-igrill@v.1.2 -- documentation needs to be updated or branch renamed

**Comment by bendikwa** [comment]
Hi! Thanks for spotting this! The correct name for the tag is v1.2  It was just a typo in the release, and should be fixed now. 👍
