### ISSUE TITLE
Typo in full_example_V2.yaml

### ISSUE THREAD

**Issue by BeFygo** [bendikwa/esphome-igrill#21]
First of all, great job!
Quick and easy install, now my Igrill V2 is usable in Home Assistant.

https://github.com/bendikwa/esphome-igrill/blob/e6cb22b887bb03a3dd3165d20e083eaab9122f8c/full_example_V2.yaml#L60C16-L60C16

While installing there was an error referring to the "space" before "binary_sensor:"

**Comment by LukasQ** [comment]
Handles by https://github.com/bendikwa/esphome-igrill/pull/22

**Comment by bendikwa** [comment]
Hi!

Thank you for reporting this, it is now fixed on main branch, 👍
