### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by soupman98** [bendikwa/esphome-igrill#27]
Still a little new to all this.. 
What if any changes have to go in the Configuration.yaml?

I added the following but am seeing this

`esp32_ble_tracker:

ble_client:
  - mac_address: 70:91:8F:98:DE:9B
    id: igrill_device98:DE:9B

sensor:
  - platform: poolmath
    url: https://api.poolmathapp.com/share/xVGGPjJ.json    

  - platform: igrill
    ble_client_id: igrill_device98:DE:9B
    update_interval: 30s # default
    battery_level:
      name: "IGrill Mini battery"
    temperature_probe1:
      name: "IGrill Mini temp probe 1"`
![image](https://github.com/user-attachments/assets/278ddb3c-8477-4c1e-93af-89600baa3c25)

**Comment by soupman98** [comment]
I got it worked out. No Configuration.yaml editing required. Mis-read the read me.

**Comment by bendikwa** [comment]
Great that you got it working. 👍
